Repository ibexa/core, pull requests merged in 2021-11, with the labels that each got.

#9 [FAST FORWARD] Merged IBX-1228 and IBX-1314 changes from ezplatform-kernel
  composer.json
  src/bundle/Core/Imagine/Cache/AliasGeneratorDecorator.php
  src/bundle/Core/Resources/config/image.yml
  src/bundle/IO/EventListener/StreamFileListener.php
  src/lib/Persistence/Cache/AbstractHandler.php
  src/lib/Persistence/Cache/AbstractInMemoryHandler.php
  src/lib/Persistence/Cache/AbstractInMemoryPersistenceHandler.php
  src/lib/Persistence/Cache/BookmarkHandler.php
  src/lib/Persistence/Cache/ContentHandler.php
  src/lib/Persistence/Cache/ContentLanguageHandler.php
  src/lib/Persistence/Cache/ContentTypeHandler.php
  src/lib/Persistence/Cache/Identifier/CacheIdentifierGenerator.php
  src/lib/Persistence/Cache/Identifier/CacheIdentifierGeneratorInterface.php
  src/lib/Persistence/Cache/Identifier/CacheIdentifierSanitizer.php
  src/lib/Persistence/Cache/LocationHandler.php
  src/lib/Persistence/Cache/LocationPathConverter.php
  src/lib/Persistence/Cache/ObjectStateHandler.php
  src/lib/Persistence/Cache/SectionHandler.php
  src/lib/Persistence/Cache/UrlAliasHandler.php
  src/lib/Persistence/Cache/UrlWildcardHandler.php
  src/lib/Persistence/Cache/UserHandler.php
  src/lib/Persistence/Legacy/Content/Language/CachingHandler.php
  src/lib/Resources/settings/storage_engines/cache.yml
  src/lib/Resources/settings/storage_engines/legacy/language.yml
  tests/lib/Persistence/Cache/AbstractBaseHandlerTest.php
  tests/lib/Persistence/Cache/BookmarkHandlerTest.php
  tests/lib/Persistence/Cache/Identifier/CacheIdentifierGeneratorTest.php
  tests/lib/Persistence/Cache/Identifier/CacheIdentifierSanitizerTest.php
  tests/lib/Persistence/Cache/LocationHandlerTest.php
  tests/lib/Persistence/Cache/LocationPathConverterTest.php
  tests/lib/Persistence/Cache/UserHandlerTest.php
  tests/lib/Persistence/Legacy/Content/Language/CachingLanguageHandlerTest.php
Labels: Fast-forward merge, Work in progress

#10 MERGE IBX-1201: Added handling of already generated aliases during subtree copying
  src/lib/Persistence/Legacy/Content/UrlAlias/Handler.php
  tests/integration/Core/Repository/LocationServiceTest.php
Labels: Bug, Ready for review

#12 Merged up ezsystems/ezplatform-kernel#249
  src/bundle/Core/DependencyInjection/EzPublishCoreExtension.php
  src/lib/Repository/Mapper/ContentLocationMapper/ContentLocationMapper.php
  src/lib/Repository/Mapper/ContentLocationMapper/DecoratedLocationService.php
  src/lib/Repository/Mapper/ContentLocationMapper/InMemoryContentLocationMapper.php
  src/lib/Repository/Mapper/Readme.md
  src/lib/Resources/settings/content_location_mapper.yml
  tests/integration/Core/LegacyTestContainerBuilder.php
  tests/lib/Repository/Mapper/ContentLocationMapper/DecoratedLocationServiceTest.php
  tests/lib/Repository/Mapper/ContentLocationMapper/InMemoryContentLocationMapperTest.php
Labels: Fast-forward merge, Feature

#17 IBX-1466: Created \Ibexa\Contracts\Core\Ibexa::VERSION contract
  src/contracts/Ibexa.php
Labels: Feature, Ready for review

#18 IBX-1466: Moved parts of EzPlatformCoreBundle to IbexaCoreBundle
  src/bundle/Core/DependencyInjection/Compiler/SessionConfigurationPass.php
  src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
  src/bundle/Core/IbexaCoreBundle.php
  src/bundle/Core/Resources/config/default_settings.yml
  tests/bundle/Core/DependencyInjection/Compiler/SessionConfigurationPassTest.php
  tests/bundle/Core/DependencyInjection/Fixtures/parameters.yml
Labels: Doc needed, Feature

#15 IBX-538: Added externally used legacy test namespaces to autoloader
  composer.json
Labels: Bug, Ready for review

#20 IBX-1308: Fixed system flag persistence while creating content type group
  src/lib/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  tests/integration/Core/Repository/ContentTypeServiceTest.php
  tests/integration/Core/Resources/settings/override.yml
Labels: Bug

#22 Ibx 1517+1518 merge up
  src/contracts/Repository/Values/Content/Query/Criterion/Ancestor.php
  src/lib/Limitation/SubtreeLimitationType.php
Labels: Bug, Fast-forward merge

#27 Merge IBX-1467: Fixed OOM regression during Subtree copying
  src/lib/Persistence/Legacy/Content/UrlAlias/Handler.php
Labels: Ready for MERGE
