Repository ibexa/core, pull requests merged in 2021-12, with the labels that each got.

#31 IBX-1589: Renamed remaining Core Extensions (IO, LSE)
  src/bundle/IO/DependencyInjection/Configuration.php
  src/bundle/IO/DependencyInjection/IbexaIOExtension.php
  src/bundle/LegacySearchEngine/DependencyInjection/IbexaLegacySearchEngineExtension.php
Labels: Feature

#36 Merge IBX-1310: Created subscriber methods for assigning/unassigning user to groups
  src/lib/Search/Common/EventSubscriber/UserEventSubscriber.php
  tests/integration/Core/Repository/UserServiceTest.php
Labels: Ready for review

#28 IBX-1580: External storage for field type settings
  src/contracts/FieldType/FieldConstraintsStorage.php
  src/contracts/Persistence/Content/Type/Handler.php
  src/lib/Persistence/Cache/ContentTypeHandler.php
  src/lib/Persistence/Legacy/Content/Type/Handler.php
  src/lib/Persistence/Legacy/Content/Type/Mapper.php
  src/lib/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  src/lib/Persistence/Legacy/Content/Type/StorageDispatcher.php
  src/lib/Persistence/Legacy/Content/Type/StorageDispatcherInterface.php
  src/lib/Persistence/Legacy/Content/Type/StorageRegistry.php
  src/lib/Persistence/Legacy/Content/Type/StorageRegistryInterface.php
  src/lib/Repository/ContentTypeService.php
  src/lib/Resources/settings/storage_engines/legacy/content_type.yml
  tests/integration/Core/FieldType/FieldConstraintsStorage/FieldConstraintsStorageTest.php
  tests/integration/Core/FieldType/FieldConstraintsStorage/Stub/ExampleFieldConstraintsStorage.php
  tests/integration/Core/FieldType/FieldConstraintsStorage/Stub/ExampleFieldType.php
  tests/integration/Core/FieldType/FieldConstraintsStorage/Stub/ExampleFieldTypeValue.php
  tests/integration/Core/LegacyTestContainerBuilder.php
  tests/integration/Core/Resources/settings/fieldtype_constraints_storage.yaml
  tests/lib/Persistence/Cache/ContentTypeHandlerTest.php
  tests/lib/Persistence/Legacy/Content/Type/ContentTypeHandlerTest.php
  tests/lib/Persistence/Legacy/Content/Type/MapperTest.php
  tests/lib/Persistence/Legacy/Content/Type/StorageDispatcherTest.php
  tests/lib/Persistence/Legacy/Content/Type/StorageRegistryTest.php
  tests/lib/Search/Legacy/Content/AbstractTestCase.php
Labels: Doc needed
