Repository ibexa/core, pull requests merged in 2022-01, with the labels that each got.

#42 IBX-1694: Dropped support for previously deprecated service tags
  phpstan-baseline.neon
  src/bundle/Core/DependencyInjection/Compiler/ContentViewPass.php
  src/bundle/Core/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPass.php
  src/bundle/Core/DependencyInjection/Compiler/LocationViewPass.php
  src/bundle/Core/DependencyInjection/Compiler/QueryTypePass.php
  src/bundle/Core/DependencyInjection/Compiler/RegisterSearchEngineIndexerPass.php
  src/bundle/Core/DependencyInjection/Compiler/RegisterSearchEnginePass.php
  src/bundle/Core/DependencyInjection/Compiler/ViewManagerPass.php
  src/bundle/Core/IbexaCoreBundle.php
  src/lib/Base/Container/Compiler/AbstractFieldTypeBasedPass.php
  src/lib/Base/Container/Compiler/Search/FieldRegistryPass.php
  src/lib/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
  src/lib/Base/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPass.php
  tests/bundle/Core/DependencyInjection/Compiler/ContentViewPassTest.php
  tests/bundle/Core/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPassTest.php
  tests/bundle/Core/DependencyInjection/Compiler/LocationViewPassTest.php
  tests/bundle/Core/DependencyInjection/Compiler/QueryTypePassTest.php
  tests/bundle/Core/DependencyInjection/Compiler/RegisterSearchEngineIndexerPassTest.php
  tests/bundle/Core/DependencyInjection/Compiler/RegisterSearchEnginePassTest.php
  tests/lib/Base/Container/Compiler/FieldTypeRegistryPassTest.php
  tests/lib/Base/Container/Compiler/Search/FieldTypeRegistryPassTest.php
  tests/lib/Base/Container/Compiler/Storage/ExternalStorageRegistryPassTest.php
Labels: Doc needed, Improvement, Ready for review

#43 Merge IBX-1182: Added cache invalidation to liip:imagine:cache:remove command
  src/bundle/Core/Imagine/Cache/AliasGeneratorDecorator.php
  src/bundle/Core/Imagine/VariationPurger/IOVariationPurger.php
  src/bundle/Core/Resources/config/image.yml
  tests/bundle/Core/Imagine/VariationPurger/IOVariationPurgerTest.php
Labels: Ready for MERGE

#45 Cross org merge
  .github/workflows/cross-merge.yaml
Labels: Ready for review

#52 Merge IBX-1392: Implemented image filenames sanitization
  src/bundle/Core/Command/NormalizeImagesPathsCommand.php
  src/bundle/Core/Resources/config/commands.yml
  src/lib/IO/FilePathNormalizer/Flysystem.php
  src/lib/Resources/settings/io.yml
  tests/integration/Core/Repository/FieldType/ImageIntegrationTest.php
  tests/integration/Core/Repository/FieldType/_fixtures/1234eeee1234-image.jpg
  tests/integration/Core/Repository/FieldType/_fixtures/2222eeee1111-image.png
  tests/lib/IO/FilePathNormalizer/FlysystemTest.php
Labels: Improvement, Ready for MERGE

#63 IBX-1696: Removed class parameters from ibexa/core repository
  src/bundle/Core/Resources/config/papi.yml
  src/bundle/Core/Resources/config/templating.yml
  src/lib/Resources/settings/indexable_fieldtypes.yml
  src/lib/Resources/settings/repository/inner.yml
Labels: Doc needed
