Repository ibexa/core, pull requests merged in 2022-12, with the labels that each got.

#170 [CI] Removed hardcoded Solr version and switched to one relying on branch-alias
  .github/workflows/ci.yaml
Labels: Ready for review

#178 [Tests] Rebranded temporary directory prefix used by Core IO tests
  src/contracts/Test/Repository/SetupFactory/Legacy.php
Labels: Bug, Ready for review

#180 IBX-4452: Moved logic to convert Limitation identifier into Label
  src/lib/Limitation/LimitationIdentifierToLabelConverter.php
  tests/lib/Limitation/LimitationIdentifierToLabelConverterTest.php
Labels: Improvement

#184 IBX-4452: Added JMSTranslation configuration and missing translations
  src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
  src/bundle/Core/Resources/config/services.yml
  src/bundle/Core/Resources/translations/forms.en.xliff
  src/bundle/Core/Translation/Policy/PolicyTranslationDefinitionProvider.php
Labels: Improvement

#186 IBX-4452: Added missing translation for content
  src/bundle/Core/Translation/Policy/PolicyTranslationDefinitionProvider.php
Labels: Improvement

#187 IBX-4452: Added missing line of translation
  src/bundle/Core/Resources/translations/forms.en.xliff
Labels: Improvement, Ready for review
