Repository ibexa/core, pull requests merged in 2022-02, with the labels that each got.

#69 [Behat] Adapted tests to the rebranding
  src/bundle/Core/Features/Context/QueryControllerContext.php
  src/bundle/Core/Features/QueryController/query_controller.feature
Labels: Ready for review

#73 Merge IBX-2098: Handled missing files in 'images:normalize-paths' command
  src/bundle/Core/Command/NormalizeImagesPathsCommand.php
Labels: Bug, Ready for MERGE

#75 IBX-1821: Changed path where translations are looked for
  src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
  src/bundle/Core/Translation/GlobCollector.php
  tests/bundle/Core/DependencyInjection/Fixtures/vendor/ibexa/i18n/translations/hi_IN/core/messages.hi_IN.xlf
  tests/bundle/Core/DependencyInjection/Fixtures/vendor/ibexa/i18n/translations/nb_NO/core/messages.nb_NO.xlf
  tests/bundle/Core/Resources/Translation/vendor/ibexa/i18n/translations/ach_UG/core/messages.ach_UG.xlf
  tests/bundle/Core/Resources/Translation/vendor/ibexa/i18n/translations/fr/admin-ui/dashboard.fr.xlf
  tests/bundle/Core/Resources/Translation/vendor/ibexa/i18n/translations/fr/core/messages.fr.xlf
  tests/bundle/Core/Resources/Translation/vendor/ibexa/i18n/translations/fr/core/wrongformat.fr.xml
  tests/bundle/Core/Resources/Translation/vendor/ibexa/i18n/translations/fr/wrongplace.fr.xml
  tests/bundle/Core/Resources/Translation/vendor/ibexa/wrong-translation-folder-format/core/messages.fr.xlf
Labels: QA approved, Ready for review
