Repository ibexa/core, pull requests merged in 2022-03, with the labels that each got.

#86 [Behat] Removed unused variable
  src/bundle/Core/Features/Context/ContentTypeContext.php
Labels: Ready for review

#88 Fix using reduce noice and swirl filters when using imagick/gmagick
  src/bundle/Core/DependencyInjection/Compiler/ImaginePass.php
Labels: Bug, QA approved

#94 Merge IBX-2264: Handled missing thumbnail images
  src/lib/FieldType/Image/ImageThumbnailStrategy.php
Labels: Ready for MERGE, Ready for review

#96 Bumped version after 4.0.3 release
  src/contracts/Ibexa.php
Labels: Ready for review
