Repository ibexa/core, pull requests merged in 2023-12, with the labels that each got.

#301 IBX-7276: Extended built-in Twig functions library
  phpstan-baseline.neon
  src/bundle/Core/Resources/config/templating.yml
  src/lib/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/UserExtension.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/ContentExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/UserExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_field_group_name.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_has_field.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/user_functions/ibexa_get_current_user.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/user_functions/ibexa_is_current_user.test
Labels: Doc needed

#291 IBX-6937: Changed maxFileSize value to float type for Image Field type
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
  src/lib/FieldType/Image/Type.php
  src/lib/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
  tests/integration/Core/Repository/FieldType/ImageIntegrationTest.php
  tests/integration/Core/Repository/_fixtures/Legacy/data/test_data.yaml
  tests/lib/FieldType/ImageTest.php
  tests/lib/Persistence/FieldValue/Converter/ImageConverterTest.php
Labels: Improvement, QA approved

#303 [CI] Added workflow for publishing the Solr image
  .github/workflows/solr.yaml
  docker/solr/Dockerfile
Labels: Ready for review

#287 IBX-6827: Aggregation API improvements
  src/contracts/Repository/Values/Content/Query/Aggregation/DateMetadataRangeAggregation.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Field/DateRangeAggregation.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Field/DateTimeRangeAggregation.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Field/FloatRangeAggregation.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Field/IntegerRangeAggregation.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Field/TimeRangeAggregation.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Range.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Ranges/DateTimeStepRangesGenerator.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Ranges/FloatStepRangesGenerator.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Ranges/IntegerStepRangesGenerator.php
  src/contracts/Repository/Values/Content/Query/Aggregation/Ranges/RangesGeneratorInterface.php
  src/contracts/Repository/Values/Content/Query/Aggregation/RawRangeAggregation.php
  src/contracts/Repository/Values/Content/Search/AggregationResult/RangeAggregationResult.php
  src/contracts/Repository/Values/Content/Search/AggregationResult/TermAggregationResult.php
  tests/integration/Core/Repository/Values/Content/Query/Aggregation/Ranges/DateTimeStepRangesGeneratorTest.php
  tests/integration/Core/Repository/Values/Content/Query/Aggregation/Ranges/FloatStepRangesGeneratorTest.php
  tests/integration/Core/Repository/Values/Content/Query/Aggregation/Ranges/IntegerStepRangesGeneratorTest.php
  tests/lib/Repository/Values/Content/Query/Aggregation/RangeTest.php
Labels: Feature

#300 IBX-6856: Added mime types limitation for ezimage field type
  phpstan-baseline.neon
  src/lib/FieldType/Image/Type.php
  src/lib/FieldType/Validator.php
  src/lib/FieldType/Validator/EmailAddressValidator.php
  src/lib/FieldType/Validator/FileExtensionBlackListValidator.php
  src/lib/FieldType/Validator/FileSizeValidator.php
  src/lib/FieldType/Validator/FloatValueValidator.php
  src/lib/FieldType/Validator/ImageValidator.php
  src/lib/FieldType/Validator/IntegerValueValidator.php
  src/lib/FieldType/Validator/StringLengthValidator.php
  src/lib/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
  src/lib/Resources/settings/fieldtypes.yml
  tests/integration/Core/Repository/FieldType/ImageIntegrationTest.php
  tests/lib/FieldType/ImageTest.php
  tests/lib/Persistence/FieldValue/Converter/ImageConverterTest.php
Labels: Feature, Ready for QA

#305 IBX-7318: Set image field from Image CT to is_searchable set to true
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
Labels: QA approved
