Repository ibexa/core, pull requests merged in 2023-10, with the labels that each got.

#270 IBX-6315: Added LocationArgumentResolver
  phpstan-baseline.neon
  src/bundle/Core/ControllerArgumentResolver/LocationArgumentResolver.php
  src/bundle/Core/Resources/config/services.yml
  tests/bundle/Core/ControllerArgumentResolver/LocationArgumentResolverTest.php
Labels: Improvement, QA approved

#280 IBX-4929: Fix PhpDoc
  phpstan-baseline.neon
  src/contracts/Container/Encore/ConfigurationDumper.php
  src/contracts/Repository/LocationService.php
  src/contracts/Search/Handler.php
Labels: Ready for review

#282 IBX-6738: Fixed content type group deletion when it contains orphaned content type drafts
  src/lib/Repository/ContentTypeService.php
  tests/integration/Core/Repository/ContentTypeServiceTest.php
Labels: Bug, QA approved
