Repository ibexa/core, pull requests merged in 2023-09, with the labels that each got.

#181 IBX-4598: Added support for generating urls for content wrappers in ibexa_url/ibexa_path
  src/contracts/Repository/Values/Content/ContentAwareInterface.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/RoutingExtension.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/RoutingExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ez_path.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ez_url.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ibexa_path.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/ibexa_url.test
Labels: Feature, Ready for review

#269 IBX-6415: Renamed domain names
  src/bundle/Core/EventListener/ExceptionListener.php
  src/bundle/Core/Resources/translations/ibexa_content_fields.en.xlf
  src/bundle/Core/Resources/translations/ibexa_fielddefinition.en.xlf
  src/bundle/Core/Resources/translations/ibexa_fieldtypes.en.xlf
  src/bundle/Core/Resources/translations/ibexa_repository_exceptions.en.xlf
  src/bundle/Core/Resources/views/content_fields.html.twig
  src/bundle/Core/Resources/views/fielddefinition_settings.html.twig
  src/lib/FieldType/Author/Type.php
  src/lib/FieldType/BinaryFile/Type.php
  src/lib/FieldType/Checkbox/Type.php
  src/lib/FieldType/Country/Type.php
  src/lib/FieldType/Date/Type.php
  src/lib/FieldType/DateAndTime/Type.php
  src/lib/FieldType/EmailAddress/Type.php
  src/lib/FieldType/Float/Type.php
  src/lib/FieldType/ISBN/Type.php
  src/lib/FieldType/Image/Type.php
  src/lib/FieldType/ImageAsset/Type.php
  src/lib/FieldType/Integer/Type.php
  src/lib/FieldType/Keyword/Type.php
  src/lib/FieldType/MapLocation/Type.php
  src/lib/FieldType/Media/Type.php
  src/lib/FieldType/Relation/Type.php
  src/lib/FieldType/RelationList/Type.php
  src/lib/FieldType/Selection/Type.php
  src/lib/FieldType/TextBlock/Type.php
  src/lib/FieldType/TextLine/Type.php
  src/lib/FieldType/Time/Type.php
  src/lib/FieldType/Url/Type.php
  src/lib/FieldType/User/Type.php
  src/lib/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
  src/lib/MVC/Symfony/Translation/ExceptionMessageTemplateFileVisitor.php
  src/lib/MVC/Symfony/Translation/FieldTypesTranslationExtractor.php
  src/lib/MVC/Symfony/Translation/TranslatableExceptionsFileVisitor.php
  src/lib/MVC/Symfony/Translation/ValidationErrorFileVisitor.php
  tests/lib/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsListTest.php
  tests/lib/MVC/Symfony/Translation/ExceptionMessageTemplateFileVisitorTest.php
Labels: Improvement

#273 Fixed PermissionResolver::canUser examples
  src/contracts/Repository/PermissionResolver.php
Labels: Bug, Rebase required

#257 IBX-6282: Added attributes support for generating name schema
  phpstan-baseline.neon
  src/contracts/Event/NameSchema/AbstractNameSchemaEvent.php
  src/contracts/Event/NameSchema/AbstractSchemaEvent.php
  src/contracts/Event/NameSchema/ContentAwareEventInterface.php
  src/contracts/Event/NameSchema/ResolveContentNameSchemaEvent.php
  src/contracts/Event/NameSchema/ResolveNameSchemaEvent.php
  src/contracts/Event/NameSchema/ResolveUrlAliasSchemaEvent.php
  src/contracts/Event/ResolveUrlAliasSchemaEvent.php
  src/contracts/Repository/NameSchema/NameSchemaServiceInterface.php
  src/contracts/Repository/NameSchema/SchemaIdentifierExtractorInterface.php
  src/lib/Repository/ContentService.php
  src/lib/Repository/EventSubscriber/NameSchemaSubscriber.php
  src/lib/Repository/Helper/NameSchemaService.php
  src/lib/Repository/NameSchema/NameSchemaService.php
  src/lib/Repository/NameSchema/SchemaIdentifierExtractor.php
  src/lib/Repository/NameSchema/UnresolvedTokenNamesException.php
  src/lib/Resources/settings/repository/inner/name_schema.yaml
  tests/lib/Repository/NameSchema/NameSchemaServiceTest.php
  tests/lib/Repository/NameSchema/SchemaIdentifierExtractorTest.php
  tests/lib/Repository/Service/Mock/ContentTest.php
Labels: QA approved, Ready for MERGE

#267 IBX-5705: Fixed handler as getTokenType returns object not id
  src/lib/Persistence/Legacy/Token/Handler.php
Labels: Ready for review

#274 IBX-5705: Fixed InteractiveLoginToken using PostAuthenticationGuardToken
  phpstan-baseline.neon
  src/lib/MVC/Symfony/Security/EventListener/SecurityListener.php
  src/lib/MVC/Symfony/Security/InteractiveLoginToken.php
Labels: QA approved

#271 IBX-6481: Fixed keys in array returned by VersionValidator::validate
  phpstan-baseline.neon
  src/contracts/Repository/Validator/ContentValidator.php
  src/contracts/Repository/Values/ContentType/FieldDefinition.php
  src/contracts/Repository/Values/ContentType/FieldDefinitionCollection.php
  src/lib/Base/Exceptions/ContentFieldValidationException.php
  src/lib/Repository/Validator/VersionValidator.php
Labels: QA approved, Ready for review
