Repository ibexa/core, pull requests merged in 2023-11, with the labels that each got.

#290 IBX-6641: "is_thumbnail" enabled by default for user_type
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
Labels: QA approved, Ready for QA

#285 IBX-6630: Allowed injecting view type into content preview controller
  phpstan-baseline.neon
  src/bundle/Core/Resources/config/routing/internal.yml
  src/lib/MVC/Symfony/Controller/Content/PreviewController.php
  tests/lib/MVC/Symfony/Controller/Controller/Content/PreviewControllerTest.php
Labels: Feature, Ready for QA

#288 IBX-6875: Implemented IsPreview View Matcher
  src/lib/MVC/Symfony/Matcher/ContentBased/IsPreview.php
  tests/lib/MVC/Symfony/Matcher/ContentBased/IsPreviewTest.php
Labels: Feature, Ready for QA

#284 IBX-6620: Added image search criterions
  .github/workflows/ci.yaml
  phpunit-integration-legacy-solr.xml
  phpunit-integration-legacy.xml
  src/contracts/Repository/Values/Content/Query/Criterion/Image.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/AbstractImageCompositeCriterion.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/AbstractImageRangeCriterion.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/Dimensions.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/FileSize.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/Height.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/MimeType.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/Orientation.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/Width.php
  src/lib/FieldType/Image/Orientation.php
  src/lib/FieldType/Image/SearchField.php
  src/lib/FieldType/Image/Type.php
  src/lib/FieldType/Image/Value.php
  src/lib/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
  tests/integration/Core/Repository/FieldType/ImageIntegrationTest.php
  tests/integration/Core/Repository/SearchServiceImageTest.php
  tests/integration/Core/Repository/_fixtures/image/landscape.jpg
  tests/integration/Core/Repository/_fixtures/image/portrait.jpg
  tests/integration/Core/Repository/_fixtures/image/square.png
  tests/integration/Core/RepositorySearchTestCase.php
  tests/lib/FieldType/ImageTest.php
Labels: Doc needed, Feature, Ready for QA
