Repository ibexa/core, pull requests merged in 2023-03, with the labels that each got.

#216 IBX-4929: Fixed PHPDoc(s) referencing `static<TValue>` return type
  src/contracts/Collection/AbstractInMemoryCollection.php
  src/contracts/Collection/StreamableInterface.php
Labels: Ready for MERGE

#220 Added ordering by Limitation identifier when loading Role
  src/lib/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
Labels: DX, Improvement, Ready for review

#215 IBX-5293: Added event dispatcher in default success handler
  src/bundle/Core/DependencyInjection/Compiler/SecurityPass.php
  src/lib/MVC/Symfony/Security/Authentication/DefaultAuthenticationSuccessHandler.php
  src/lib/MVC/Symfony/Security/Authentication/DetermineTargetUrlEvent.php
  tests/lib/MVC/Symfony/Security/Authentication/DefaultAuthenticationSuccessHandlerTest.php
Labels: QA approved

#219 IBX-4929: ContentService: Fix @see usage
  src/contracts/Repository/ContentService.php
Labels: Ready for MERGE

#218 IBX-4929: Removed reference to non-existent ObjectStateService example
  src/lib/Repository/ObjectStateService.php
Labels: Ready for review

#222 [PHPDoc] Removed `@internal param` from IOConfigurationPass::processHandlers
  src/bundle/IO/DependencyInjection/Compiler/IOConfigurationPass.php
Labels: Ready for review
