Repository ibexa/core, pull requests merged in 2023-08, with the labels that each got.

#253 Fixed deprecating `convertToEz` method
  src/lib/MVC/Symfony/Locale/LocaleConverterInterface.php
Labels: Bug, Ready for review

#249 IBX-5936: Added `ContentTypeHandler::loadContentTypesByFieldDefinitionIdentifier` method
  src/bundle/Core/Resources/config/storage/legacy/schema.yaml
  src/contracts/Persistence/Content/Type/Handler.php
  src/lib/Persistence/Cache/ContentTypeHandler.php
  src/lib/Persistence/Legacy/Content/Type/Gateway.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  src/lib/Persistence/Legacy/Content/Type/Handler.php
  src/lib/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  src/lib/Resources/settings/storage_engines/cache.yml
  tests/lib/Persistence/Cache/ContentTypeHandlerTest.php
  tests/lib/Persistence/Legacy/Content/Type/ContentTypeHandlerTest.php
Labels: Bug, QA approved

#204 IBX-5061: Improved readability for DateMetadata criterion targets
  src/contracts/Repository/Values/Content/Query/Criterion/DateMetadata.php
  src/lib/Search/Legacy/Content/Common/Gateway/CriterionHandler/DateMetadata.php
  tests/lib/Repository/Values/Content/Query/Criterion/DateMetadataTest.php
Labels: Improvement, Ready for review

#266 Improved specificity for View's template identifier Closure
  src/lib/MVC/Symfony/View/BaseView.php
  src/lib/MVC/Symfony/View/View.php
Labels: Improvement, Ready for review

#268 Increased PHPStan level to 8
  composer.json
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  phpstan-baseline.neon
  phpstan-baseline.neon.php
  phpstan.neon.dist
  src/lib/FieldType/Author/AuthorCollection.php
Labels: Improvement, Ready for review
