Repository ibexa/core, pull requests merged in 2023-07, with the labels that each got.

#240 IBX-5915: Added way to revoke existing token
  src/bundle/Core/Resources/config/storage/legacy/schema.yaml
  src/contracts/Persistence/Token/Handler.php
  src/contracts/Persistence/Token/Token.php
  src/contracts/Repository/Decorator/TokenServiceDecorator.php
  src/contracts/Repository/Events/Token/BeforeRevokeTokenByIdentifierEvent.php
  src/contracts/Repository/Events/Token/BeforeRevokeTokenEvent.php
  src/contracts/Repository/Events/Token/RevokeTokenByIdentifierEvent.php
  src/contracts/Repository/Events/Token/RevokeTokenEvent.php
  src/contracts/Repository/TokenService.php
  src/contracts/Repository/Values/Token/Token.php
  src/lib/Event/TokenService.php
  src/lib/Persistence/Legacy/Token/Gateway/Token/Doctrine/DoctrineGateway.php
  src/lib/Persistence/Legacy/Token/Gateway/Token/Gateway.php
  src/lib/Persistence/Legacy/Token/Handler.php
  src/lib/Persistence/Legacy/Token/Mapper.php
  src/lib/Repository/TokenService.php
  tests/integration/Core/Repository/TokenServiceTest.php
Labels: Ready for MERGE

#245 IBX-4853: Deprecated `Ibexa\Core\MVC\Symfony\Locale::convertToEz` method
  src/lib/MVC/Symfony/Locale/LocaleConverter.php
  src/lib/MVC/Symfony/Locale/LocaleConverterInterface.php
  tests/lib/MVC/Symfony/Locale/LocaleConverterTest.php
Labels: Bug, QA approved, Ready for MERGE

#242 IBX-5630: Added possibility to extend URL schema resolving
  src/bundle/Core/ApiLoader/RepositoryFactory.php
  src/bundle/Core/Resources/config/events.yml
  src/bundle/Core/Resources/config/papi.yml
  src/contracts/Event/ResolveUrlAliasSchemaEvent.php
  src/contracts/Repository/NameSchema/NameSchemaServiceInterface.php
  src/contracts/Repository/NameSchema/SchemaIdentifierExtractorInterface.php
  src/contracts/Test/IbexaKernelTestTrait.php
  src/contracts/Test/IbexaTestKernel.php
  src/lib/Base/Container/ApiLoader/RepositoryFactory.php
  src/lib/Repository/ContentService.php
  src/lib/Repository/EventSubscriber/NameSchemaSubscriber.php
  src/lib/Repository/Helper/NameSchemaService.php
  src/lib/Repository/LocationService.php
  src/lib/Repository/NameSchema/NameSchemaService.php
  src/lib/Repository/NameSchema/SchemaIdentifierExtractor.php
  src/lib/Repository/Repository.php
  src/lib/Repository/TrashService.php
  src/lib/Repository/URLAliasService.php
  src/lib/Resources/settings/events.yml
  src/lib/Resources/settings/repository/inner.yml
  src/lib/Resources/settings/repository/inner/name_schema.yaml
  tests/integration/Core/Repository/LocationServiceTest.php
  tests/integration/Core/Repository/URLAliasService/UrlAliasLookupTest.php
  tests/integration/Core/Repository/UserServiceTest.php
  tests/integration/Core/RepositoryTestCase.php
  tests/integration/Core/Resources/settings/common.yml
  tests/integration/Core/Resources/settings/integration_legacy.yml
  tests/lib/Repository/ContentServiceTest.php
  tests/lib/Repository/NameSchema/NameSchemaServiceTest.php
  tests/lib/Repository/NameSchema/SchemaIdentifierExtractorTest.php
  tests/lib/Repository/Service/Mock/Base.php
  tests/lib/Repository/Service/Mock/ContentTest.php
  tests/lib/Repository/Service/Mock/NameSchemaTest.php
Labels: QA approved, Ready for MERGE

#248 IBX-6202: Fixed url alias grouping
  src/lib/Repository/NameSchema/NameSchemaService.php
  src/lib/Repository/NameSchema/SchemaIdentifierExtractor.php
  tests/lib/Repository/NameSchema/SchemaIdentifierExtractorTest.php
Labels: QA approved
