Repository ibexa/core, pull requests merged in 2024-04, with the labels that each got.

#349 IBX-7717: Introduced strict getters for LookupLimitationResult and VersionInfo Value Object
  src/contracts/Repository/Values/Content/VersionInfo.php
  src/contracts/Repository/Values/User/LookupLimitationResult.php
Labels: QA approved, Ready for review

#354 IBX-8032: Added proper casting to int for width/height in image search field
  src/lib/FieldType/Image/SearchField.php
Labels: Bug, QA approved

#343 IBX-7833: [PAPI] Implemented loading paginated relation list
  phpstan-baseline.neon
  src/contracts/Persistence/Content/Handler.php
  src/contracts/Repository/ContentService.php
  src/contracts/Repository/Decorator/ContentServiceDecorator.php
  src/lib/Persistence/Cache/ContentHandler.php
  src/lib/Persistence/Legacy/Content/Gateway.php
  src/lib/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  src/lib/Persistence/Legacy/Content/Handler.php
  src/lib/Repository/ContentService.php
  src/lib/Repository/SiteAccessAware/ContentService.php
  src/lib/Resources/settings/storage_engines/cache.yml
  tests/integration/Core/Repository/ContentServiceTest.php
  tests/lib/Persistence/Cache/ContentHandlerTest.php
  tests/lib/Repository/SiteAccessAware/ContentServiceTest.php
Labels: Bug, QA approved

#344 [BC break] Added `implements \Stringable` to `Translation` Value Object
  phpstan-baseline.neon
  src/contracts/Repository/Values/Translation.php
  src/contracts/Repository/Values/Translation/Message.php
  src/contracts/Repository/Values/Translation/Plural.php
Labels: Improvement, Ready for review

#358 IBX-8119: Upgraded minimum PHP version to 8.3
  .github/workflows/ci.yaml
  .github/workflows/gha-docker-solr.yaml
  composer.json
Labels: Ready for review
