Repository ibexa/core, pull requests merged in 2024-10, with the labels that each got.

#431 Regenerated PHPStan baseline
  phpstan-baseline.neon
Labels: Ready for review

#420 IBX-8811: Rebranded SiteAccess session prefix
  phpstan-baseline.neon
  src/bundle/Core/DependencyInjection/Configuration/Parser/Common.php
  src/bundle/Core/EventListener/SessionSetDynamicNameListener.php
  src/bundle/Core/Resources/config/default_settings.yml
  tests/bundle/Core/EventListener/SessionInitByPostListenerTest.php
  tests/bundle/Core/EventListener/SessionSetDynamicNameListenerTest.php
  tests/lib/MVC/Symfony/Component/Serializer/SimplifiedRequestNormalizerTest.php
Labels: Doc needed, QA approved

#433 Fixed issues found by by PHPStan
  phpstan-baseline-7.4.neon
  phpstan-baseline-gte-8.0.neon
  src/bundle/Core/Features/Context/BasicContentContext.php
Labels: Bug

#436 [Composer] Dropped ibexa/ci-scripts from dev requirements
  composer.json
Labels: Improvement, Ready for review

#440 IBX-9103: Add RelationType for filtering purposes to fetch relations methods
  src/contracts/Repository/ContentService.php
  src/contracts/Repository/Decorator/ContentServiceDecorator.php
  src/contracts/Repository/Values/Content/Relation.php
  src/contracts/Repository/Values/Content/RelationType.php
  src/lib/Repository/ContentService.php
  src/lib/Repository/SiteAccessAware/ContentService.php
  tests/integration/Core/Repository/ContentServiceTest.php
Labels: Ready for review

#441 Optimized content thumbnail resolving
  src/lib/Repository/Strategy/ContentThumbnail/FirstMatchingFieldStrategy.php
Labels: Improvement, QA approved, Ready for review

#442 Reduced row extraction time complexity from n^2 to 2n in persistence content type mapper
  src/lib/Persistence/Legacy/Content/Type/Mapper.php
Labels: QA approved
