Repository ibexa/core, pull requests merged in 2024-01, with the labels that each got.

#313 IBX-7337: Added twig functions to get user preference
  src/bundle/Core/Resources/config/templating.yml
  src/lib/MVC/Symfony/Templating/Twig/Extension/UserPreferenceExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/UserPreferenceRuntime.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/UserPreferenceExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/user_preference_functions/get_user_preference_value.function.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/user_preference_functions/has_user_preference.function.test
Labels: QA approved

#318 Fixed incorrect list of excluded dirs for JMS translation extraction
  src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
  src/bundle/Core/Resources/translations/repository_exceptions.en.xlf
Labels: Bug

#320 IBX-7502: Added file size validation for image asset field type
  phpstan-baseline.neon
  src/lib/FieldType/ImageAsset/Type.php
  src/lib/Resources/settings/fieldtypes.yml
  tests/lib/FieldType/ImageAssetTest.php
Labels: Bug, QA approved

#312 IBX-7418: Added ContentNameCriterion
  src/contracts/Repository/Values/Content/Query/Criterion/ContentName.php
  src/lib/Resources/settings/search_engines/legacy/criterion_handlers_common.yml
  src/lib/Search/Legacy/Content/Common/Gateway/CriterionHandler/ContentName.php
  tests/integration/Core/Repository/SearchServiceContentNameTest.php
Labels: Doc needed, Feature, QA approved

#325 [Fast forward] Merged branch '4.5'
  phpstan-baseline-7.4.neon
  phpstan-baseline.neon
Labels: Fast-forward merge

#319 IBX-5821: Fixed an issue where incomplete request object was passed over to route Matcher
  phpstan-baseline.neon
  src/bundle/Core/Routing/DefaultRouter.php
  tests/bundle/Core/Routing/DefaultRouterTest.php
Labels: Bug, QA approved, Ready for review
