Repository ibexa/core, pull requests merged in 2024-08, with the labels that each got.

#405 IBX-8558: Removed `GuardRepositoryAuthenticationProvider` due to Symfony security deprecations
  phpstan-baseline.neon
  src/bundle/Core/DependencyInjection/Compiler/SecurityPass.php
  src/lib/MVC/Symfony/Security/Authentication/GuardRepositoryAuthenticationProvider.php
  tests/bundle/Core/DependencyInjection/Compiler/SecurityPassTest.php
  tests/lib/MVC/Symfony/Security/Authentication/GuardRepositoryAuthenticationProviderTest.php
Labels: Doc needed, QA approved

#410 IBX-4000: Changed the method name creation for logCall in callable function
  src/lib/Persistence/Cache/ObjectStateHandler.php
  tests/lib/Persistence/Cache/AbstractCacheHandlerTest.php
Labels: Bug, QA approved

#418 [PHPStan] Aligned baseline after PHPStan release
  phpstan-baseline.neon
Labels: Ready for MERGE, Ready for review

#414 IBX-8469: Fixed image filtering by file size float value
  src/contracts/Repository/Values/Content/Query/Criterion/Image/AbstractImageRangeCriterion.php
  src/contracts/Repository/Values/Content/Query/Criterion/Image/FileSize.php
  tests/integration/Core/Repository/SearchServiceImageTest.php
Labels: Bug, QA approved, Ready for MERGE

#421 [Tests] Truncated SQLite last insert ID to real DB integer value
  src/lib/Persistence/Legacy/SharedGateway/DatabasePlatform/SqliteGateway.php
Labels: Improvement, Ready for review

#422 Extracted redundant TextLine and ISBN SearchField into a common base
  src/lib/FieldType/BaseSingleTextLineSearchField.php
  src/lib/FieldType/ISBN/SearchField.php
  src/lib/FieldType/TextLine/SearchField.php
Labels: Improvement, Ready for review

#424 Extracted abstract for redundant Host & URI text matchers
  phpstan-baseline.neon
  src/lib/MVC/Symfony/SiteAccess/Matcher/AffixBasedTextMatcher.php
  src/lib/MVC/Symfony/SiteAccess/Matcher/HostText.php
  src/lib/MVC/Symfony/SiteAccess/Matcher/URIText.php
Labels: Improvement, Ready for review
