Repository ibexa/core, pull requests merged in 2024-07, with the labels that each got.

#375 IBX-8356: Removed `Ibexa\Core\MVC\Symfony\Security\Authentication\AuthenticatorInterface` to be replaced with Symfony-based authentication
  src/bundle/Core/DependencyInjection/Compiler/SecurityPass.php
  src/bundle/Core/Resources/config/security.yml
  src/lib/MVC/Symfony/Security/Authentication/AuthenticatorInterface.php
  src/lib/MVC/Symfony/Security/Authentication/DefaultAuthenticationSuccessHandler.php
  src/lib/MVC/Symfony/Security/Authentication/EventSubscriber/OnAuthenticationTokenCreatedRepositoryUserSubscriber.php
  tests/lib/MVC/Symfony/Security/Authentication/EventSubscriber/OnAuthenticationTokenCreatedRepositoryUserSubscriberTest.php
Labels: Doc needed, QA approved

#394 IBX-8452: Fixed string substitution for Plural Value Object when casting to string
  phpstan-baseline.neon
  src/contracts/Repository/Values/Translation/Message.php
  src/contracts/Repository/Values/Translation/Plural.php
  tests/lib/Repository/Values/Translation/MessageTest.php
  tests/lib/Repository/Values/Translation/PluralTest.php
Labels: Ready for QA, Ready for review

#399 Regenerated PHPStan baseline
  phpstan-baseline.neon
  tests/bundle/Core/EventSubscriber/TrustedHeaderClientIpEventSubscriberTest.php
Labels: Ready for review

#397 [PHPDoc] Improved definitions
  phpstan-baseline.neon
  src/contracts/FieldType/FieldType.php
  src/contracts/FieldType/GatewayBasedStorage.php
  src/contracts/Limitation/Type.php
  src/contracts/Persistence/Content/ContentInfo.php
  src/contracts/Persistence/Content/Location.php
  src/contracts/Persistence/Content/Location/CreateStruct.php
  src/contracts/Persistence/Content/Type.php
  src/contracts/Persistence/Content/Type/Handler.php
  src/contracts/Persistence/Content/VersionInfo.php
  src/contracts/Repository/ContentService.php
  src/contracts/Repository/ContentTypeService.php
  src/contracts/Repository/FieldType.php
  src/contracts/Repository/LocationService.php
  src/contracts/Repository/UserService.php
  src/contracts/Repository/Values/Content/Content.php
  src/contracts/Repository/Values/Content/Query/Criterion/FieldRelation.php
  src/contracts/Repository/Values/Content/Query/Criterion/FullText.php
  src/contracts/Repository/Values/Content/Relation.php
  src/contracts/Repository/Values/Content/VersionInfo.php
  src/contracts/Repository/Values/User/Role.php
  src/contracts/Search/Field.php
Labels: Ready for MERGE

#401 Deprecated `CONSTANT_AUTH_TIME_SETTING`
  src/bundle/Core/DependencyInjection/Compiler/SecurityPass.php
Labels: Doc needed, Ready for MERGE, Ready for review

#396 IBX-8323: Reworked RepositoryAuthenticationProvider and moved its logic to a dedicated subscriber
  phpstan-baseline.neon
  src/bundle/Core/DependencyInjection/Compiler/SecurityPass.php
  src/bundle/Core/Resources/config/security.yml
  src/lib/MVC/Symfony/Security/Authentication/EventSubscriber/RepositoryUserAuthenticationSubscriber.php
  src/lib/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProvider.php
  src/lib/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php
  tests/bundle/Core/DependencyInjection/Compiler/SecurityPassTest.php
  tests/lib/MVC/Symfony/Security/Authentication/EventSubscriber/RepositoryUserAuthenticationSubscriberTest.php
  tests/lib/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProviderTest.php
  tests/lib/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProviderTest.php
Labels: Bug, Doc needed, Feature, QA approved

#390 IBX-8426: Fixed duplicate relations
  src/lib/Repository/ContentService.php
  tests/integration/Core/Repository/ContentService/UpdateContentTest.php
  tests/integration/Core/RepositoryTestCase.php
  tests/lib/Repository/Service/Mock/ContentTest.php
Labels: QA approved, Ready for review

#400 IBX-8138: Refactored deprecated `loadUserByUsername` method in custom providers
  phpstan-baseline.neon
  src/contracts/Repository/UserService.php
  src/lib/MVC/Symfony/Security/User/EmailProvider.php
  src/lib/MVC/Symfony/Security/User/UsernameProvider.php
  tests/lib/MVC/Symfony/Security/User/BaseProviderTestCase.php
  tests/lib/MVC/Symfony/Security/User/EmailProviderTest.php
  tests/lib/MVC/Symfony/Security/User/UsernameProviderTest.php
Labels: QA approved, Ready for review

#409 IBX-8644: Added missing country Curaçao in ezcountry fieldtype
  src/lib/Resources/settings/fieldtypes.yml
Labels: QA approved
