Repository ibexa/core, pull requests merged in 2024-05, with the labels that each got.

#361 IBX-8012: `UrlAliasGenerator` should load location with provided `languages`
  phpstan-baseline.neon
  src/lib/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
  tests/lib/MVC/Symfony/Routing/UrlAliasGeneratorTest.php
Labels: Bug, QA approved

#370 IBX-8283: Added missing translations
  src/bundle/Core/Resources/translations/forms.en.xlf
  src/bundle/Core/Translation/Policy/PolicyTranslationDefinitionProvider.php
Labels: Bug, Ready for review

#371 [PHPStan] Aligned baseline with the new version of PHPStan
  phpstan-baseline-gte-8.0.neon
  phpstan-baseline-lte-8.1.neon
  phpstan-baseline-lte-8.2.neon
  phpstan-baseline.neon
  phpstan-baseline.neon.php
  tests/lib/Repository/User/PasswordHashServiceTest.php
Labels: Improvement, Ready for review

#333 IBX-7653: IsContainer criterion added
  .sonarcloud.properties
  src/contracts/Repository/Values/Content/Query/Criterion/IsContainer.php
  src/lib/Persistence/Legacy/Filter/CriterionQueryBuilder/Content/IsContainerQueryBuilder.php
  src/lib/Resources/settings/search_engines/legacy/criterion_handlers_common.yml
  src/lib/Search/Legacy/Content/Common/Gateway/CriterionHandler/IsContainer.php
  tests/integration/Core/Repository/Filtering/BaseRepositoryFilteringTestCase.php
  tests/integration/Core/Repository/SearchServiceTest.php
  tests/integration/Core/Repository/_fixtures/Legacy/IsContainerFalse.php
  tests/integration/Core/Repository/_fixtures/Legacy/IsContainerTrue.php
Labels: QA approved

#350 IBX-3957: Made NOP URL aliases not reusable and original
  src/lib/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/UrlAlias/Handler.php
  tests/integration/Core/Repository/URLAliasServiceTest.php
Labels: Bug, Doc needed, QA approved, Ready for MERGE
