Repository ibexa/core, pull requests merged in 2024-02, with the labels that each got.

#327 IBX-7278: Set proper route defaults values
  src/bundle/Core/Resources/config/routing/internal.yml
Labels: QA approved

#322 IBX-6906: [DX] Introduced identifier-based view matchers
  phpstan-baseline.neon
  src/bundle/Core/DependencyInjection/Compiler/ViewMatcherRegistryPass.php
  src/bundle/Core/IbexaCoreBundle.php
  src/bundle/Core/Matcher/ServiceAwareMatcherFactory.php
  src/bundle/Core/Matcher/ViewMatcherRegistry.php
  src/bundle/Core/Resources/config/templating.yml
  src/contracts/MVC/View/ViewMatcherRegistryInterface.php
  src/lib/MVC/Symfony/Matcher/ClassNameMatcherFactory.php
  tests/bundle/Core/DependencyInjection/Compiler/ViewMatcherRegistryPassTest.php
  tests/bundle/Core/Matcher/ServiceAwareMatcherFactoryTest.php
  tests/bundle/Core/Matcher/ViewMatcherRegistryTest.php
Labels: Doc needed, Improvement, QA approved, Ready for review

#328 Specified return type for PermissionResolver
  phpstan-baseline.neon
  src/contracts/Repository/PermissionResolver.php
Labels: Improvement, Ready for review

#329 IBX-7689: Modified code to generate hyperlinks only for non-drafts
  src/bundle/Core/Resources/views/default/content/embed.html.twig
Labels: Bug, QA approved

#304 [CI] Improvements to Solr image publishing
  .github/workflows/gha-docker-solr.yaml
  .github/workflows/solr.yaml
Labels: Ready for review

#332 IBX-7744: Updated Ibexa logo
  src/bundle/Debug/Resources/views/Profiler/layout.html.twig
Labels: Improvement, QA approved

#323 IBX-7364: Ensured independent property assignment in setPreviewActive method by using clone
  src/lib/Helper/ContentPreviewHelper.php
  tests/lib/Helper/ContentPreviewHelperTest.php
Labels: QA approved

#335 Fix typo in ibexa:install option description
  src/bundle/RepositoryInstaller/Command/InstallPlatformCommand.php
Labels: Bug

#331 IBX-7636: Prevented caching content preview response
  src/lib/MVC/Symfony/Controller/Content/PreviewController.php
Labels: Bug, QA approved

#338 [Composer] Dropped obsolete symfony/thanks config
  composer.json
Labels: Improvement

#341 IBX-7838: Corrected message an error for InvalidArgumentType
  phpstan-baseline.neon
  src/lib/Limitation/RoleLimitationType.php
Labels: Bug, Ready for review
