Repository ibexa/core, pull requests merged in 2024-06, with the labels that each got.

#376 Merge remote-tracking branch 'origin/4.6' into 'main'
  COPYRIGHT
  LICENSE
  phpstan-baseline.neon
  src/contracts/Event/Mapper/ResolveMissingFieldEvent.php
  src/contracts/FieldType/DefaultDataFieldStorage.php
  src/contracts/Repository/Values/Content/Field.php
  src/lib/Persistence/Legacy/Content/FieldHandler.php
  src/lib/Persistence/Legacy/Content/Mapper.php
  src/lib/Persistence/Legacy/Content/Mapper/ResolveVirtualFieldSubscriber.php
  src/lib/Persistence/Legacy/Content/StorageHandler.php
  src/lib/Persistence/Legacy/Content/Type/Handler.php
  src/lib/Persistence/Legacy/Content/Type/Update/Handler/DoctrineDatabase.php
  src/lib/Persistence/Legacy/SharedGateway/DatabasePlatform/SqliteGateway.php
  src/lib/Resources/settings/storage_engines/legacy/content.yml
  src/lib/Resources/settings/storage_engines/legacy/content_type.yml
  tests/integration/Core/Repository/ContentTypeServiceTest.php
  tests/integration/Core/Resources/settings/common.yml
  tests/lib/Persistence/Legacy/Content/Mapper/ResolveVirtualFieldSubscriberTest.php
  tests/lib/Persistence/Legacy/Content/MapperTest.php
  tests/lib/Persistence/Legacy/Content/StorageHandlerTest.php
  tests/lib/Persistence/Legacy/Content/Type/ContentTypeHandlerTest.php
  tests/lib/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabaseTest.php
  tests/lib/Persistence/Legacy/Content/Type/Update/Handler/DoctrineDatabaseTest.php
  tests/lib/Persistence/Legacy/Content/_fixtures/extract_content_from_rows_result.php
  tests/lib/Persistence/Legacy/SharedGateway/GatewayFactoryTest.php
  tests/lib/Persistence/Legacy/TestCase.php
  tests/lib/Search/Legacy/Content/AbstractTestCase.php
  tests/lib/Search/Legacy/Content/HandlerContentSortTest.php
  tests/lib/Search/Legacy/Content/HandlerContentTest.php
Labels: Ready for review

#383 IBX-8399: Moved RepositoryConfigurationProvider to Repository layer
  phpstan-baseline.neon
  src/bundle/Core/ApiLoader/Exception/InvalidRepositoryException.php
  src/bundle/Core/ApiLoader/Exception/InvalidSearchEngine.php
  src/bundle/Core/ApiLoader/Exception/InvalidSearchEngineIndexer.php
  src/bundle/Core/ApiLoader/Exception/InvalidStorageEngine.php
  src/bundle/Core/ApiLoader/RepositoryConfigurationProvider.php
  src/bundle/Core/ApiLoader/RepositoryFactory.php
  src/bundle/Core/ApiLoader/SearchEngineFactory.php
  src/bundle/Core/ApiLoader/SearchEngineIndexerFactory.php
  src/bundle/Core/ApiLoader/StorageConnectionFactory.php
  src/bundle/Core/ApiLoader/StorageEngineFactory.php
  src/bundle/Core/Command/CleanupVersionsCommand.php
  src/bundle/Core/DependencyInjection/Compiler/StorageConnectionFactoryPass.php
  src/bundle/Core/Entity/EntityManagerFactory.php
  src/bundle/Core/IbexaCoreBundle.php
  src/bundle/Core/Resources/config/papi.yml
  src/bundle/Core/Resources/config/services.yml
  src/bundle/Core/Resources/config/storage_engines.yml
  src/bundle/LegacySearchEngine/ApiLoader/ConnectionFactory.php
  src/bundle/LegacySearchEngine/Resources/config/services.yml
  src/bundle/RepositoryInstaller/Command/InstallPlatformCommand.php
  src/bundle/RepositoryInstaller/Resources/config/services.yml
  src/contracts/Container/ApiLoader/RepositoryConfigurationProviderInterface.php
  src/lib/Base/Container/ApiLoader/RepositoryConfigurationProvider.php
  src/lib/Helper/FieldsGroups/RepositoryConfigFieldsGroupsListFactory.php
  tests/bundle/Core/ApiLoader/BaseRepositoryConfigurationProviderTestCase.php
  tests/bundle/Core/ApiLoader/RepositoryConfigurationProviderTest.php
  tests/bundle/Core/ApiLoader/StorageConnectionFactoryTest.php
  tests/bundle/Core/ApiLoader/StorageEngineFactoryTest.php
  tests/bundle/Core/DependencyInjection/Compiler/EntityManagerFactoryServiceLocatorPassTest.php
  tests/bundle/Core/DependencyInjection/Compiler/StorageConnectionFactoryPassTest.php
  tests/bundle/Core/Entity/EntityManagerFactoryTest.php
  tests/lib/Helper/FieldsGroups/RepositoryConfigFieldsGroupsListFactoryTest.php
Labels: Improvement, Ready for review

#384 IBX-8400: Fixed redundancy in RepositoryFactory implementations
  phpstan-baseline.neon
  src/bundle/Core/ApiLoader/RepositoryFactory.php
  src/bundle/Core/Resources/config/papi.yml
  src/bundle/Core/Resources/config/storage_engines.yml
  src/contracts/Repository/RoleService.php
  src/lib/Base/Container/ApiLoader/RepositoryFactory.php
  src/lib/Repository/RoleService.php
  src/lib/Resources/settings/repository/autowire.yml
  src/lib/Resources/settings/repository/inner.yml
  tests/integration/Core/Resources/settings/integration_legacy.yml
Labels: Improvement, Ready for review, Rebase required

#387 IBX-8356: Deprecated `Ibexa\Core\MVC\Symfony\Security\Authentication\AuthenticatorInterface` to be replaced with Symfony-based authorization in 5.0
  phpstan-baseline.neon
  src/lib/MVC/Symfony/Security/Authentication/AuthenticatorInterface.php
Labels: Doc needed, Ready for review

#392 IBX-8136: Dropped "guzzlehttp/guzzle" and "php-http/guzzle6-adapter" dependencies
  composer.json
Labels: Ready for review
