Repository ibexa/core, pull requests merged in 2024-11, with the labels that each got.

#379 [PHPDoc] Improved ContentService doc for API reference
  phpstan-baseline-7.4.neon
  phpstan-baseline-gte-8.0.neon
  phpstan-baseline.neon
  src/contracts/Repository/ContentService.php
Labels: Ready for review

#439 IBX-8418: Remove draft when trashing or deleting its parent or ancestor location
  phpstan-baseline.neon
  src/contracts/Persistence/Content/Location/Handler.php
  src/contracts/Test/IbexaKernelTestTrait.php
  src/contracts/Test/IbexaTestKernel.php
  src/lib/Persistence/Cache/LocationHandler.php
  src/lib/Persistence/Legacy/Content/Handler.php
  src/lib/Persistence/Legacy/Content/Location/Gateway.php
  src/lib/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  src/lib/Persistence/Legacy/Content/Location/Handler.php
  src/lib/Persistence/Legacy/Content/TreeHandler.php
  src/lib/Repository/TrashService.php
  tests/integration/Core/Repository/ContentService/DeleteContentTest.php
  tests/lib/Persistence/Cache/LocationHandlerTest.php
  tests/lib/Persistence/Legacy/Content/LocationHandlerTest.php
  tests/lib/Persistence/Legacy/Content/TreeHandlerTest.php
Labels: Bug, QA approved

#451 Merge 4.6 into main
  phpstan-baseline.neon
  src/contracts/Persistence/Content/Location/Handler.php
  src/contracts/Repository/ContentService.php
  src/contracts/Test/IbexaKernelTestTrait.php
  src/contracts/Test/IbexaTestKernel.php
  src/lib/Persistence/Cache/LocationHandler.php
  src/lib/Persistence/Legacy/Content/Handler.php
  src/lib/Persistence/Legacy/Content/Location/Gateway.php
  src/lib/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  src/lib/Persistence/Legacy/Content/Location/Handler.php
  src/lib/Persistence/Legacy/Content/TreeHandler.php
  src/lib/Repository/TrashService.php
  tests/integration/Core/Repository/ContentService/DeleteContentTest.php
  tests/lib/Persistence/Cache/LocationHandlerTest.php
  tests/lib/Persistence/Legacy/Content/LocationHandlerTest.php
  tests/lib/Persistence/Legacy/Content/TreeHandlerTest.php
Labels: Fast-forward merge

#455 Fixed issues related to twig/twig 3.15 in tests
  phpstan-baseline.neon
  src/lib/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/DataAttributesExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/DeprecationOptionsTrait.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/FieldRenderingExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/FileSizeExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/ImageExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/QueryRenderingExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/RenderContentExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/RenderExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/RenderLocationExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/RoutingExtension.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/DataAttributesExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/FileSizeExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/RoutingExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/filters/7.4/ez_data_attributes_serialize.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/filters/7.4/ibexa_data_attributes_serialize.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/filters/8.0/ez_data_attributes_serialize.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/filters/8.0/ibexa_data_attributes_serialize.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/functions/ez_file_size/7.4/ez_file_size.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/functions/ez_file_size/7.4/ibexa_file_size.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/functions/ez_file_size/8.0/ez_file_size.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/functions/ez_file_size/8.0/ibexa_file_size.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/functions/ez_file_size/ez_file_size.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/7.4/ez_path.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/7.4/ez_route.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/7.4/ez_url.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/7.4/ibexa_path.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/7.4/ibexa_route.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/7.4/ibexa_url.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/8.0/ez_path.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/8.0/ez_route.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/8.0/ez_url.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/8.0/ibexa_path.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/8.0/ibexa_route.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/routing_functions/8.0/ibexa_url.test
Labels: Improvement

#452 Introduced StructValidator to unpack validation errors for structs
  src/bundle/Core/Resources/config/services.yml
  src/contracts/Validation/AbstractValidationStructWrapper.php
  src/contracts/Validation/StructValidator.php
  src/contracts/Validation/StructWrapperValidator.php
  src/contracts/Validation/ValidationFailedException.php
  src/contracts/Validation/ValidationStructWrapperInterface.php
  tests/lib/Validation/StructValidatorTest.php
  tests/lib/Validation/StructWrapperValidatorTest.php
  tests/lib/Validation/ValidationFailedExceptionTest.php
Labels: Improvement, Ready for review

#454 IBX-8566: Fixed postgres language limit
  src/lib/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Language/MaskGenerator.php
  src/lib/Persistence/Legacy/Content/Mapper.php
  src/lib/Persistence/Legacy/SharedGateway/DatabasePlatform/AbstractGateway.php
  src/lib/Persistence/Legacy/SharedGateway/DatabasePlatform/FallbackGateway.php
  src/lib/Persistence/Legacy/SharedGateway/DatabasePlatform/PostgresqlGateway.php
  src/lib/Persistence/Legacy/SharedGateway/DatabasePlatform/SqliteGateway.php
  src/lib/Persistence/Legacy/SharedGateway/Gateway.php
  src/lib/Resources/settings/storage_engines/legacy/shared_gateway.yaml
  tests/integration/Core/Repository/ContentService/MaxLanguagesContentServiceTest.php
  tests/integration/Core/Repository/_fixtures/max_languages.yaml
  tests/lib/Persistence/Legacy/SharedGateway/GatewayFactoryTest.php
  tests/lib/Persistence/Legacy/TestCase.php
Labels: Bug, QA approved
