Repository ibexa/core, pull requests merged in 2025-06, with the labels that each got.

#573 Corrected PHPDoc for removeFieldDefinition() param
  phpstan-baseline.neon
  src/contracts/Persistence/Content/Type/Handler.php
Labels: Ready for review

#594 IBX-9328: Added the `users_group_root_subtree_path` config parameter
  src/bundle/Core/DependencyInjection/Configuration/Parser/Common.php
  src/bundle/Core/Resources/config/default_settings.yml
Labels: Improvement, Ready for review

#592 IBX-8697: Added validation for Keyword field type values in content and tests
  src/lib/FieldType/Keyword/Type.php
  tests/lib/FieldType/KeywordTest.php
Labels: Ready for QA, Ready for review
