Repository ibexa/core, pull requests merged in 2025-07, with the labels that each got.

#603 IBX-10167: Fixed translations export in abstract field type classes
  src/bundle/Core/Resources/translations/ibexa_fieldtypes.en.xlf
  src/lib/FieldType/BaseNumericType.php
  src/lib/FieldType/BaseTextType.php
  src/lib/FieldType/Float/Type.php
  src/lib/FieldType/Integer/Type.php
  src/lib/FieldType/TextBlock/Type.php
  src/lib/FieldType/TextLine/Type.php
Labels: Bug, QA approved

#606 IBX-10229: Made old field type alias fallback to new one in searchable field map
  src/lib/Persistence/Legacy/Content/Type/Handler.php
  src/lib/Resources/settings/storage_engines/legacy/content_type.yml
  tests/lib/Persistence/Legacy/Content/Type/ContentTypeHandlerTest.php
  tests/lib/Search/Legacy/Content/AbstractTestCase.php
Labels: Bug, Ready for QA

#618 Changed pattern to vhost compatible
  src/bundle/Core/EventListener/RejectExplicitFrontControllerRequestsListener.php
  tests/bundle/Core/EventListener/RejectExplicitFrontControllerRequestsListenerTest.php
Labels: Bug, Ready for review

#595 IBX-10159: Corrected generate dfs_database_url parameter for Ibexa Cloud
  src/bundle/Core/DependencyInjection/IbexaCoreExtension.php
  tests/bundle/Core/DependencyInjection/IbexaCoreExtensionTest.php
  tests/bundle/Core/Resources/config/packages/dfs/dfs.yaml
Labels: Bug, QA approved

#579 IBX-10116: Fixed `ibexa_render()` not using decorated fragment renders
  src/contracts/MVC/Templating/BaseRenderStrategy.php
  tests/lib/MVC/Symfony/Templating/RenderContentStrategyTest.php
Labels: QA approved

#623 IBX-10263: Allowed hyphens in HostText and UriText siteaccess matchers
  src/lib/MVC/Symfony/SiteAccess/Matcher/HostText.php
  src/lib/MVC/Symfony/SiteAccess/Matcher/URIText.php
  tests/lib/MVC/Symfony/SiteAccess/RouterHostTextTest.php
Labels: QA approved

#627 IBX-9060: Updated StatusCriterionHandler to use `in` expression for multi-status support
  src/lib/Persistence/Legacy/Notification/Gateway/CriterionHandler/StatusCriterionHandler.php
Labels: Ready for review
