Repository ibexa/core, pull requests merged in 2025-10, with the labels that each got.

#652 IBX-10597: Fixed accessing uninitialized image variation properties when switching to the original variation
  phpstan-baseline.neon
  src/bundle/Core/Imagine/AliasGenerator.php
  src/lib/Repository/LocationService.php
  tests/bundle/Core/Imagine/AliasGeneratorTest.php
  tests/bundle/IO/.gitkeep
  tests/integration/Core/Repository/Regression/EZP21798Test.php
  tests/integration/Core/Repository/URLWildcardServiceTest.php
  tests/lib/Repository/Values/User/RoleTest.php
  tests/lib/Repository/Values/User/UserTest.php
Labels: Bug, QA approved

#633 IBX-10458: Implemented new Content Type search PHP API
  .github/workflows/browser-tests.yaml
  src/contracts/Persistence/Content/Type/CriterionHandlerInterface.php
  src/contracts/Persistence/Content/Type/Handler.php
  src/contracts/Repository/ContentTypeService.php
  src/contracts/Repository/Decorator/ContentTypeServiceDecorator.php
  src/contracts/Repository/Values/ContentType/Query/ContentTypeQuery.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/ContainsFieldDefinitionId.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/ContentTypeGroupId.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/ContentTypeId.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/ContentTypeIdentifier.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/IsSystem.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/LogicalAnd.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/LogicalNot.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/LogicalOperator.php
  src/contracts/Repository/Values/ContentType/Query/Criterion/LogicalOr.php
  src/contracts/Repository/Values/ContentType/Query/CriterionInterface.php
  src/contracts/Repository/Values/ContentType/Query/SortClause.php
  src/contracts/Repository/Values/ContentType/Query/SortClause/Id.php
  src/contracts/Repository/Values/ContentType/Query/SortClause/Identifier.php
  src/contracts/Repository/Values/ContentType/Query/SortClause/Name.php
  src/contracts/Repository/Values/ContentType/SearchResult.php
  src/lib/Persistence/Cache/ContentTypeHandler.php
  src/lib/Persistence/Legacy/Content/Type/Gateway.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/ContainsFieldDefinitionId.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/ContentTypeGroupId.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/ContentTypeId.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/ContentTypeIdentifier.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/IsSystem.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/LogicalAnd.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/LogicalNot.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionHandler/LogicalOr.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/CriterionVisitor/CriterionVisitor.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  src/lib/Persistence/Legacy/Content/Type/Handler.php
  src/lib/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  src/lib/Repository/ContentTypeService.php
  src/lib/Repository/SiteAccessAware/ContentTypeService.php
  src/lib/Resources/settings/storage_engines/legacy/content_type.yml
  tests/integration/Core/Repository/ContentTypeService/FindContentTypesTest.php
  tests/lib/Persistence/Legacy/Content/LanguageAwareTestCase.php
  tests/lib/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabaseTest.php
  tests/lib/Repository/SiteAccessAware/ContentTypeServiceTest.php
  tests/lib/Search/Legacy/Content/AbstractTestCase.php
Labels: Doc needed, Feature, Ready for review

#657 [CI] Bumped actions' versions + regenerated PHPStan baseline
  .github/workflows/ci.yaml
  phpstan-baseline.neon
Labels: Ready for review
