Repository ibexa/core, pull requests merged in 2025-04, with the labels that each got.

#510 IBX-9060: Added mark as unread functionality for notifications
  phpstan-baseline.neon
  src/contracts/Repository/Decorator/NotificationServiceDecorator.php
  src/contracts/Repository/Events/Notification/BeforeMarkNotificationAsUnreadEvent.php
  src/contracts/Repository/Events/Notification/MarkNotificationAsUnreadEvent.php
  src/contracts/Repository/NotificationService.php
  src/lib/Event/NotificationService.php
  src/lib/Repository/NotificationService.php
  src/lib/Repository/SiteAccessAware/NotificationService.php
  tests/integration/Core/Repository/NotificationServiceTest.php
  tests/lib/Event/NotificationServiceTest.php
  tests/lib/Repository/Decorator/NotificationServiceDecoratorTest.php
Labels: Ready for review

#515 IBX-9379: Added Grace Period for archived versions
  bootstrap.php
  phpstan-baseline.neon
  src/bundle/Core/ApiLoader/RepositoryFactory.php
  src/bundle/Core/DependencyInjection/Configuration/Parser/Repository/Options.php
  src/bundle/Core/EventSubscriber/ClearCollectedContentCacheSubscriber.php
  src/bundle/Core/Resources/config/services.yml
  src/contracts/Persistence/Content/Handler.php
  src/lib/Base/Container/ApiLoader/RepositoryFactory.php
  src/lib/Persistence/Cache/ContentHandler.php
  src/lib/Persistence/Legacy/Content/Gateway.php
  src/lib/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  src/lib/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
  src/lib/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  src/lib/Persistence/Legacy/Content/Handler.php
  src/lib/Repository/Collector/ContentCollector.php
  src/lib/Repository/ContentService.php
  src/lib/Repository/Repository.php
  src/lib/Resources/settings/repository/inner.yml
  tests/integration/Core/Repository/ContentServiceTest.php
  tests/integration/Core/Repository/UserServiceTest.php
  tests/lib/Repository/ContentServiceTest.php
  tests/lib/Repository/Service/Mock/Base.php
  tests/lib/Repository/Service/Mock/ContentTest.php
Labels: QA approved

#521 IBX-9810: Fixed inner `validateProperty*()` calls of StructWrapperValidator
  .github/workflows/ci.yaml
  src/contracts/Validation/StructWrapperValidator.php
  tests/lib/Validation/StructWrapperValidatorTest.php
Labels: QA approved

#514 Remove usage of deprecated ContainerAwareTrait
  phpstan-baseline.neon
  src/bundle/Core/ApiLoader/CacheFactory.php
  src/bundle/Core/DependencyInjection/Configuration/ConfigResolver.php
  src/bundle/Core/DependencyInjection/Configuration/ConfigResolver/ContainerConfigResolver.php
  src/bundle/Core/DependencyInjection/Configuration/ConfigResolver/DefaultScopeConfigResolver.php
  src/bundle/Core/DependencyInjection/Configuration/ConfigResolver/GlobalScopeConfigResolver.php
  src/bundle/Core/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolver.php
  src/bundle/Core/DependencyInjection/Configuration/ConfigResolver/StaticSiteAccessConfigResolver.php
  src/bundle/Core/Resources/config/cache.yml
  src/bundle/Core/Resources/config/services.yml
  src/bundle/IO/DependencyInjection/Compiler/IOConfigurationPass.php
  src/bundle/IO/DependencyInjection/ConfigurationFactory.php
  src/bundle/IO/DependencyInjection/ConfigurationFactory/Flysystem.php
  src/bundle/IO/DependencyInjection/ConfigurationFactory/MetadataHandler/LegacyDFSCluster.php
  src/bundle/LegacySearchEngine/ApiLoader/ConnectionFactory.php
  src/bundle/LegacySearchEngine/Resources/config/services.yml
  src/lib/MVC/Symfony/Controller/Content/DownloadController.php
  src/lib/MVC/Symfony/Controller/Content/DownloadRedirectionController.php
  src/lib/MVC/Symfony/Controller/Content/ViewController.php
  src/lib/MVC/Symfony/Controller/Controller.php
  tests/bundle/Core/ApiLoader/CacheFactoryTest.php
  tests/bundle/Core/ConfigResolverTest.php
  tests/bundle/Core/DependencyInjection/Configuration/ConfigResolver/ChainConfigResolverTest.php
  tests/bundle/Core/DependencyInjection/Configuration/ConfigResolver/DefaultScopeConfigResolverTest.php
  tests/bundle/Core/DependencyInjection/Configuration/ConfigResolver/GlobalScopeConfigResolverTest.php
  tests/bundle/Core/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolverTest.php
  tests/bundle/Core/DependencyInjection/Configuration/ConfigResolver/StaticSiteAccessConfigResolverTest.php
  tests/bundle/Core/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
  tests/bundle/IO/DependencyInjection/ConfigurationFactoryTest.php
  tests/integration/Core/Resources/settings/common.yml
  tests/lib/MVC/Symfony/Controller/ControllerTest.php
Labels: QA approved

#525 IBX-9898: Added mandatory admin user password altering on `ibexa:install`
  phpstan-baseline.neon
  src/bundle/RepositoryInstaller/Command/InstallPlatformCommand.php
Labels: Doc needed, Improvement, QA approved
