Repository ibexa/core, pull requests merged in 2025-02, with the labels that each got.

#468 IBX-9421: Fixed global `@serializer` service overwriting Ibexa serializer variant
  src/bundle/Core/Resources/config/routing.yml
Labels: QA approved

#471 IBX-9326: Fixed missing class attribute for image field Twig block
  src/bundle/Core/Resources/views/content_fields.html.twig
Labels: QA approved

#474 IBX-9513: Fixed obsolete `ibexa_*` Controller references
  src/bundle/Core/Features/QueryController/setup.feature
  src/bundle/Core/Resources/views/content_fields.html.twig
  src/lib/MVC/Symfony/View/Builder/ContentViewBuilder.php
  tests/lib/MVC/Symfony/View/Builder/ContentViewBuilderTest.php
Labels: QA approved

#467 IBX-9415: Added support for ContentAwareInterface in ibexa_* Twig functions
  src/lib/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/FieldRenderingExtension.php
  src/lib/MVC/Symfony/Templating/Twig/Extension/RenderContentExtension.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/ContentExtensionTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/FieldRenderingExtensionIntegrationTest.php
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ez_content_field_identifier_first_filled_image.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ez_field.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ez_field_description.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ez_field_name.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ez_field_value.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ez_is_field_empty.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_content_field_identifier_first_filled_image.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_content_name.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_field.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_field_description.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_field_name.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_field_value.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_has_field.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/content_functions/ibexa_is_field_empty.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/field_rendering_functions/ez_render_field.test
  tests/lib/MVC/Symfony/Templating/Twig/Extension/_fixtures/field_rendering_functions/ibexa_render_field.test
Labels: Doc needed, Ready for QA

#464 IBX-9302: Improved default image variations to auto rotate
  src/bundle/Core/Resources/config/default_settings.yml
Labels: QA approved, Ready for review

#481 Merged branch '4.6' into main
  phpstan-baseline.neon
  src/bundle/Core/Resources/config/default_settings.yml
  src/contracts/FieldType/FieldType.php
  src/contracts/FieldType/Generic/Type.php
  src/contracts/FieldType/Generic/ValidationError/ConstraintViolationAdapter.php
  src/contracts/Limitation/Target/Builder/VersionBuilder.php
  src/contracts/Limitation/Type.php
  src/contracts/Repository/LocationService.php
  src/contracts/Repository/SearchService.php
  src/contracts/Repository/Values/Content/Location.php
  src/contracts/Repository/Values/Content/Query/Criterion.php
  src/contracts/Repository/Values/Content/Query/Criterion/DateMetadata.php
  src/contracts/Repository/Values/Content/Query/Criterion/Operator/Specifications.php
  src/contracts/Repository/Values/Content/Query/Criterion/UserMetadata.php
  src/contracts/Repository/Values/ValueObject.php
  src/contracts/Search/Capable.php
  tests/integration/Core/Repository/SearchServiceTest.php
Labels: Fast-forward merge

#487 Refactored DateMapper for better date conversion handling and code readability
  src/lib/Search/Common/FieldValueMapper/DateMapper.php
Labels: Ready for review

#489 Refactored SearchResult::$count to SearchResult::$totalCount deprecation
  phpstan-baseline.neon
  src/contracts/Repository/Values/Content/Trash/SearchResult.php
  tests/integration/Core/Repository/TrashServiceTest.php
Labels: Ready for review
